export interface VerifiedPdfShade {
  shade_code: string;
  shade_name: string;
  category: string;
  color_family: string;
  hex_color: string;
  pdf_source: string;
  pdf_page: number;
}

export const VERIFIED_PDF_SHADES: VerifiedPdfShade[] = [
  // ================= EXTERIORS SHADE PALETTE =================
  // --- Right Whites (Exteriors Page 3) ---
  { shade_code: "1093", shade_name: "Pebble's Sound", category: "Right Whites", color_family: "White", hex_color: "#F3EFE0", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "1112", shade_name: "Wing Shimmer", category: "Right Whites", color_family: "White", hex_color: "#FCF8F4", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "1096", shade_name: "Clotted Crème", category: "Right Whites", color_family: "White", hex_color: "#FAF5E1", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "1114", shade_name: "Calm Breeze", category: "Right Whites", color_family: "White", hex_color: "#FBF3DE", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "1097", shade_name: "Convent Lace", category: "Right Whites", color_family: "White", hex_color: "#FAF5DD", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "1117", shade_name: "Fountain’s Pool", category: "Right Whites", color_family: "White", hex_color: "#FFFDF2", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "1127", shade_name: "Milk of Ambrosia", category: "Right Whites", color_family: "Orange", hex_color: "#FFF1DF", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "1135", shade_name: "Alabaster Shell", category: "Right Whites", color_family: "Orange", hex_color: "#FFEADA", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "1196", shade_name: "Stray Light", category: "Right Whites", color_family: "White", hex_color: "#FAF8F5", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "1021", shade_name: "Snow Drift", category: "Right Whites", color_family: "White", hex_color: "#F7F9FA", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "1057", shade_name: "Shore Side Haze", category: "Right Whites", color_family: "White", hex_color: "#F5F5ED", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "1024", shade_name: "Winter Time", category: "Right Whites", color_family: "White", hex_color: "#EFF3EF", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "1066", shade_name: "Antique Pearl", category: "Right Whites", color_family: "White", hex_color: "#F7F5EA", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "1156", shade_name: "Himalayan Air", category: "Right Whites", color_family: "White", hex_color: "#F3EEF5", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "1058", shade_name: "Homestead Beige", category: "Right Whites", color_family: "White", hex_color: "#F2EDE2", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "1016", shade_name: "Peace Plaza", category: "Right Whites", color_family: "White", hex_color: "#EDF2E8", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },

  // --- Fresh Pastels (Exteriors Page 3) ---
  { shade_code: "2043", shade_name: "Champagne Glass", category: "Fresh Pastels", color_family: "Yellow", hex_color: "#FDF1D5", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "2038", shade_name: "Happy Time", category: "Fresh Pastels", color_family: "Yellow", hex_color: "#E8F086", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "2046", shade_name: "Morning Mimosa", category: "Fresh Pastels", color_family: "Yellow", hex_color: "#FFE59E", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "2054", shade_name: "Wood Shaving", category: "Fresh Pastels", color_family: "Yellow", hex_color: "#D6D99C", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "2091", shade_name: "Fresh Aroma", category: "Fresh Pastels", color_family: "Yellow", hex_color: "#FAF2D5", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "2095", shade_name: "Warm Crust", category: "Fresh Pastels", color_family: "Yellow", hex_color: "#FBE6BE", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "2221", shade_name: "Kiss of Light", category: "Fresh Pastels", color_family: "Yellow", hex_color: "#FFF3DC", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "2295", shade_name: "Sensual Silk", category: "Fresh Pastels", color_family: "Pink", hex_color: "#F9D5CE", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "2312", shade_name: "Garden Flowers", category: "Fresh Pastels", color_family: "Pink", hex_color: "#FFD0D9", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "2307", shade_name: "Floating Parasol", category: "Fresh Pastels", color_family: "Pink", hex_color: "#F0B5CE", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "2385", shade_name: "Marine Drive", category: "Fresh Pastels", color_family: "Blue", hex_color: "#CAD6ED", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "2398", shade_name: "Beach Side", category: "Fresh Pastels", color_family: "Blue", hex_color: "#A8BBE5", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "2464", shade_name: "Ripple of Rain", category: "Fresh Pastels", color_family: "Blue", hex_color: "#ACD2E2", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "2466", shade_name: "Flight of Pigeons", category: "Fresh Pastels", color_family: "Blue", hex_color: "#C7E5EC", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "2604", shade_name: "Scented Eucalyptus", category: "Fresh Pastels", color_family: "Green", hex_color: "#AEDBA7", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "2687", shade_name: "Nutty Season", category: "Fresh Pastels", color_family: "Green", hex_color: "#E7ECB4", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },

  // --- Modern Midtones (Exteriors Page 3) ---
  { shade_code: "3032", shade_name: "Jaipur Gate", category: "Modern Midtones", color_family: "Yellow", hex_color: "#CCCA91", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "3016", shade_name: "Dancing Girl", category: "Modern Midtones", color_family: "Yellow", hex_color: "#D8BF50", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "3054", shade_name: "Jai Mandir", category: "Modern Midtones", color_family: "Yellow", hex_color: "#CDBC72", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "3056", shade_name: "Patina Gold", category: "Modern Midtones", color_family: "Yellow", hex_color: "#F6C561", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "3093", shade_name: "Rock Plaster", category: "Modern Midtones", color_family: "Brown", hex_color: "#C4AC79", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "3156", shade_name: "Madhubani Orange", category: "Modern Midtones", color_family: "Orange", hex_color: "#FA9D6D", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "3154", shade_name: "Story Telling", category: "Modern Midtones", color_family: "Orange", hex_color: "#FCA45A", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "3216", shade_name: "Rose Madder", category: "Modern Midtones", color_family: "Red", hex_color: "#E96C61", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "3212", shade_name: "Organic Dye", category: "Modern Midtones", color_family: "Brown", hex_color: "#D6B794", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "3275", shade_name: "Amethyst Cluster", category: "Modern Midtones", color_family: "Pink", hex_color: "#B8838B", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "3292", shade_name: "City Lore", category: "Modern Midtones", color_family: "Grey", hex_color: "#DFCDBC", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "3354", shade_name: "Divine Blue", category: "Modern Midtones", color_family: "Blue", hex_color: "#94AEBA", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "3404", shade_name: "Graceful Run", category: "Modern Midtones", color_family: "Green", hex_color: "#AEBFAF", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "3444", shade_name: "Sailing Tide", category: "Modern Midtones", color_family: "Green", hex_color: "#91C8AD", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "3615", shade_name: "Tea Tasting", category: "Modern Midtones", color_family: "Green", hex_color: "#CCD7AD", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },
  { shade_code: "3596", shade_name: "Pagoda Green", category: "Modern Midtones", color_family: "Green", hex_color: "#BCD449", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 3 },

  // --- Modern Midtones (Exteriors Page 4) ---
  { shade_code: "3037", shade_name: "Battlement", category: "Modern Midtones", color_family: "Yellow", hex_color: "#CCAF35", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "3066", shade_name: "Hidden Cove", category: "Modern Midtones", color_family: "Yellow", hex_color: "#CCA330", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "3076", shade_name: "Pagoda Roof", category: "Modern Midtones", color_family: "Yellow", hex_color: "#EAA61E", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "3097", shade_name: "Maze of Lanes", category: "Modern Midtones", color_family: "Yellow", hex_color: "#D69F21", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "3158", shade_name: "Natural Pigment", category: "Modern Midtones", color_family: "Orange", hex_color: "#C96D2D", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "3187", shade_name: "Dark Umber", category: "Modern Midtones", color_family: "Brown", hex_color: "#834A42", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "3198", shade_name: "Inner City Walls", category: "Modern Midtones", color_family: "Red", hex_color: "#B8543B", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "3207", shade_name: "Classic Red", category: "Modern Midtones", color_family: "Red", hex_color: "#9E1917", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "3268", shade_name: "Velvet Field", category: "Modern Midtones", color_family: "Red", hex_color: "#9E2954", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "3306", shade_name: "Kings Mantle", category: "Modern Midtones", color_family: "Violet", hex_color: "#C599D9", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "3347", shade_name: "Majorelle Ceramic", category: "Modern Midtones", color_family: "Blue", hex_color: "#7E8AA3", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "3357", shade_name: "Gopurum Gate", category: "Modern Midtones", color_family: "Blue", hex_color: "#4A6380", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "3406", shade_name: "Water Canal", category: "Modern Midtones", color_family: "Blue", hex_color: "#94B5B2", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "3388", shade_name: "Ebb and Tide", category: "Modern Midtones", color_family: "Blue", hex_color: "#3B6E6A", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "3555", shade_name: "Monsoon Green", category: "Modern Midtones", color_family: "Green", hex_color: "#5EA95C", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "3487", shade_name: "Ocean Deep", category: "Modern Midtones", color_family: "Green", hex_color: "#37634C", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },

  // --- Smart Neutrals (Exteriors Page 4) ---
  { shade_code: "4061", shade_name: "Transcript", category: "Smart Neutrals", color_family: "Grey", hex_color: "#E1DACF", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "4111", shade_name: "Light Within", category: "Smart Neutrals", color_family: "White", hex_color: "#EFE8DC", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "4063", shade_name: "Papyrus", category: "Smart Neutrals", color_family: "Yellow", hex_color: "#CBC4A3", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "4112", shade_name: "Lapsed Time", category: "Smart Neutrals", color_family: "Yellow", hex_color: "#DFD2B5", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "4075", shade_name: "Dense Thicket", category: "Smart Neutrals", color_family: "Green", hex_color: "#8A7942", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "4093", shade_name: "Riviera Sand", category: "Smart Neutrals", color_family: "Yellow", hex_color: "#C9BF9E", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "4067", shade_name: "Composition", category: "Smart Neutrals", color_family: "Brown", hex_color: "#5F4D32", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "4356", shade_name: "Red Ore", category: "Smart Neutrals", color_family: "Red", hex_color: "#A6513A", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "4292", shade_name: "Still Quiet", category: "Smart Neutrals", color_family: "Green", hex_color: "#E7F5D6", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "4222", shade_name: "Elemental Sheen", category: "Smart Neutrals", color_family: "Green", hex_color: "#CEDCC4", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "4294", shade_name: "Inner View", category: "Smart Neutrals", color_family: "Green", hex_color: "#A2A77B", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "4264", shade_name: "Rushing Wave", category: "Smart Neutrals", color_family: "Green", hex_color: "#CDD4B4", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "4394", shade_name: "Sustainability Now", category: "Smart Neutrals", color_family: "Green", hex_color: "#7E901F", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "4267", shade_name: "Endless Sound", category: "Smart Neutrals", color_family: "Green", hex_color: "#637666", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "4295", shade_name: "Therapy Green", category: "Smart Neutrals", color_family: "Green", hex_color: "#95A26B", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "4385", shade_name: "Next Crest", category: "Smart Neutrals", color_family: "Green", hex_color: "#466543", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },

  // --- Bold Accents (Exteriors Page 4) ---
  { shade_code: "5026", shade_name: "Brocade Bravado", category: "Bold Accents", color_family: "Yellow", hex_color: "#EAB01D", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "5034", shade_name: "Temple Of The Sun", category: "Bold Accents", color_family: "Yellow", hex_color: "#F9B80F", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "5077", shade_name: "Rusty Hue", category: "Bold Accents", color_family: "Orange", hex_color: "#DC591E", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "5086", shade_name: "Halon Wash", category: "Bold Accents", color_family: "Red", hex_color: "#FC3A07", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "5132", shade_name: "Smart Pink", category: "Bold Accents", color_family: "Pink", hex_color: "#E3066C", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "5125", shade_name: "Take The Stage", category: "Bold Accents", color_family: "Red", hex_color: "#DC0B24", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "5161", shade_name: "Leader Of The Pink", category: "Bold Accents", color_family: "Pink", hex_color: "#EA1280", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "5163", shade_name: "Daddy’s Girl", category: "Bold Accents", color_family: "Pink", hex_color: "#D60C72", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "5182", shade_name: "Nectar In A Sieve", category: "Bold Accents", color_family: "Pink", hex_color: "#E74FEA", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "5174", shade_name: "Fauvelot Color", category: "Bold Accents", color_family: "Pink", hex_color: "#B83D6D", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "5192", shade_name: "Blue Rain", category: "Bold Accents", color_family: "Violet", hex_color: "#6951C2", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "5207", shade_name: "While It Lasts", category: "Bold Accents", color_family: "Blue", hex_color: "#222C74", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "5252", shade_name: "Enchantment Tokyo", category: "Bold Accents", color_family: "Green", hex_color: "#0BC672", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "5225", shade_name: "Good Time", category: "Bold Accents", color_family: "Green", hex_color: "#0EA484", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "5305", shade_name: "In The Limelight", category: "Bold Accents", color_family: "Yellow", hex_color: "#EBE312", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },
  { shade_code: "5315", shade_name: "I’m Happy Now", category: "Bold Accents", color_family: "Yellow", hex_color: "#E6DC17", pdf_source: "Colourvista Shade Palette - Exteriors", pdf_page: 4 },

  // ================= INTERIORS SHADE PALETTE =================
  // --- Right Whites (Interiors Page 3) ---
  { shade_code: "1081", shade_name: "Cream Damask", category: "Right Whites", color_family: "White", hex_color: "#F6F5E3", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "1141", shade_name: "Promised White", category: "Right Whites", color_family: "White", hex_color: "#FAF0EC", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "1094", shade_name: "White Window", category: "Right Whites", color_family: "White", hex_color: "#FCFCE8", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "1132", shade_name: "Fuchsia Hint", category: "Right Whites", color_family: "White", hex_color: "#FCF3EB", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "1088", shade_name: "Lifelong Dream", category: "Right Whites", color_family: "White", hex_color: "#FAF8E1", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "1123", shade_name: "Tender Skin", category: "Right Whites", color_family: "White", hex_color: "#FCEFE0", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "1074", shade_name: "Cotton Pods", category: "Right Whites", color_family: "White", hex_color: "#FAFAE1", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "1087", shade_name: "Vintage Theme", category: "Right Whites", color_family: "White", hex_color: "#F6ECD2", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "1191", shade_name: "White Palace", category: "Right Whites", color_family: "White", hex_color: "#FAFDFC", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "1013", shade_name: "White Inspiration", category: "Right Whites", color_family: "White", hex_color: "#FCF1F3", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "1031", shade_name: "Wisp of Vapor", category: "Right Whites", color_family: "White", hex_color: "#FAFDFC", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "1103", shade_name: "Composed Verse", category: "Right Whites", color_family: "White", hex_color: "#F4F6E9", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "1053", shade_name: "Vap", category: "Right Whites", color_family: "White", hex_color: "#F8FAF3", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "1014", shade_name: "Artist’s White", category: "Right Whites", color_family: "White", hex_color: "#EFF0EC", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "1047", shade_name: "Simplicity Itself", category: "Right Whites", color_family: "White", hex_color: "#ECEDDD", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "1167", shade_name: "Incense Haze", category: "Right Whites", color_family: "White", hex_color: "#EBE3E9", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },

  // --- Smart Neutrals (Interiors Page 3) ---
  { shade_code: "4071", shade_name: "Raw Wood", category: "Smart Neutrals", color_family: "Yellow", hex_color: "#ECE4C3", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "4181", shade_name: "Acoustic", category: "Smart Neutrals", color_family: "Violet", hex_color: "#E2D9EB", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "4091", shade_name: "Material Chic", category: "Smart Neutrals", color_family: "Yellow", hex_color: "#DCD0B1", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "4161", shade_name: "Digital Life", category: "Smart Neutrals", color_family: "Violet", hex_color: "#E3D6E1", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "4103", shade_name: "Sensual Shade", category: "Smart Neutrals", color_family: "Brown", hex_color: "#AA8A71", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "4163", shade_name: "The Cloud", category: "Smart Neutrals", color_family: "Violet", hex_color: "#A28E9A", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "4094", shade_name: "Designer’s Neutral", category: "Smart Neutrals", color_family: "Grey", hex_color: "#837C76", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "4195", shade_name: "Mirror Foil", category: "Smart Neutrals", color_family: "Grey", hex_color: "#5C5A65", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "4031", shade_name: "Once Upon A Time", category: "Smart Neutrals", color_family: "Grey", hex_color: "#E3E7DF", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "4191", shade_name: "Looking Glass", category: "Smart Neutrals", color_family: "Violet", hex_color: "#E7DCF5", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "4301", shade_name: "Calm Serenity", category: "Smart Neutrals", color_family: "Green", hex_color: "#CEDAC3", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "4202", shade_name: "Ethere Star", category: "Smart Neutrals", color_family: "Grey", hex_color: "#CDD4D2", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "4054", shade_name: "Reflective", category: "Smart Neutrals", color_family: "Green", hex_color: "#B2AA8F", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "4213", shade_name: "Perihelion", category: "Smart Neutrals", color_family: "Green", hex_color: "#A2AAA2", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "4314", shade_name: "Weathered Clay", category: "Smart Neutrals", color_family: "Green", hex_color: "#83835B", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "4215", shade_name: "Umbra", category: "Smart Neutrals", color_family: "Grey", hex_color: "#767671", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },

  // --- Fresh Pastels (Interiors Page 3) ---
  { shade_code: "2013", shade_name: "January Moon", category: "Fresh Pastels", color_family: "Green", hex_color: "#EDFCDE", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "2045", shade_name: "Glazed Macaroon", category: "Fresh Pastels", color_family: "Yellow", hex_color: "#FAF8C0", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "2063", shade_name: "Kesari Cream", category: "Fresh Pastels", color_family: "Yellow", hex_color: "#FAE4AD", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "2104", shade_name: "Marigold Petals", category: "Fresh Pastels", color_family: "Yellow", hex_color: "#FBDE94", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "2103", shade_name: "Beige Trail", category: "Fresh Pastels", color_family: "Yellow", hex_color: "#FBE6BE", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "2144", shade_name: "Perfect Puff", category: "Fresh Pastels", color_family: "Orange", hex_color: "#FFE8D2", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "2202", shade_name: "Pink Slip", category: "Fresh Pastels", color_family: "Pink", hex_color: "#FCD0CF", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "2224", shade_name: "Beach Peach", category: "Fresh Pastels", color_family: "Orange", hex_color: "#FFDCC0", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "2303", shade_name: "Wishing Wand", category: "Fresh Pastels", color_family: "Pink", hex_color: "#FFCAD4", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "2325", shade_name: "Exotic Beauty", category: "Fresh Pastels", color_family: "Pink", hex_color: "#FFB8DC", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "2343", shade_name: "Innocent Thought", category: "Fresh Pastels", color_family: "Blue", hex_color: "#E2EEFF", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "2365", shade_name: "Moody Blues", category: "Fresh Pastels", color_family: "Blue", hex_color: "#C2CEFC", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "2424", shade_name: "Candy Cloud", category: "Fresh Pastels", color_family: "Blue", hex_color: "#C7EDFF", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "2395", shade_name: "Cumulous Cloud", category: "Fresh Pastels", color_family: "Blue", hex_color: "#BEC7F0", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "2594", shade_name: "Painted Fern", category: "Fresh Pastels", color_family: "Green", hex_color: "#C2EDCE", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },
  { shade_code: "2643", shade_name: "Pleasing Green", category: "Fresh Pastels", color_family: "Green", hex_color: "#DAFAA2", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 3 },

  // --- Fresh Pastels (Interiors Page 4) ---
  { shade_code: "2027", shade_name: "Summer Time", category: "Fresh Pastels", color_family: "Yellow", hex_color: "#FAF821", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "2056", shade_name: "Sunset Hill", category: "Fresh Pastels", color_family: "Yellow", hex_color: "#FACC67", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "2067", shade_name: "Mango Shake", category: "Fresh Pastels", color_family: "Yellow", hex_color: "#FAB231", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "2097", shade_name: "Tea Shop", category: "Fresh Pastels", color_family: "Yellow", hex_color: "#FFAE34", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "2146", shade_name: "Clam Shell", category: "Fresh Pastels", color_family: "Orange", hex_color: "#FFAC67", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "2207", shade_name: "Screen Goddess", category: "Fresh Pastels", color_family: "Orange", hex_color: "#FFA27C", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "2265", shade_name: "Baby Pink", category: "Fresh Pastels", color_family: "Pink", hex_color: "#FFBAC8", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "2267", shade_name: "Rainbow Rocket", category: "Fresh Pastels", color_family: "Pink", hex_color: "#FFA2AA", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "2326", shade_name: "Elusive Wilderness", category: "Fresh Pastels", color_family: "Violet", hex_color: "#ECD4FC", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "2357", shade_name: "Lyrical Lilac", category: "Fresh Pastels", color_family: "Violet", hex_color: "#CCB2FC", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "2386", shade_name: "Arabian Sea", category: "Fresh Pastels", color_family: "Blue", hex_color: "#CED9FB", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "2408", shade_name: "Daytime Moon", category: "Fresh Pastels", color_family: "Blue", hex_color: "#A2C2F6", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "2463", shade_name: "Indian Roller Bird", category: "Fresh Pastels", color_family: "Green", hex_color: "#CCEDD1", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "2486", shade_name: "Tropical Palm", category: "Fresh Pastels", color_family: "Blue", hex_color: "#A2FCF1", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "2605", shade_name: "Green Glade", category: "Fresh Pastels", color_family: "Green", hex_color: "#C5EDA1", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "2688", shade_name: "Chlorophyll Drink", category: "Fresh Pastels", color_family: "Green", hex_color: "#CEF63C", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },

  // --- Modern Midtones (Interiors Page 4) ---
  { shade_code: "3011", shade_name: "Indus Valley", category: "Modern Midtones", color_family: "Green", hex_color: "#D6DE9F", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "3052", shade_name: "Marble Screen", category: "Modern Midtones", color_family: "Yellow", hex_color: "#D6D19E", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "3051", shade_name: "Hill View", category: "Modern Midtones", color_family: "Yellow", hex_color: "#EBE3A2", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "3055", shade_name: "Courtyard Yellow", category: "Modern Midtones", color_family: "Yellow", hex_color: "#FCBF49", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "3091", shade_name: "Rice Husk", category: "Modern Midtones", color_family: "Yellow", hex_color: "#DECFA2", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "3134", shade_name: "Carved Doorway", category: "Modern Midtones", color_family: "Orange", hex_color: "#DDAC82", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "3261", shade_name: "Mineral Hill", category: "Modern Midtones", color_family: "Brown", hex_color: "#EFE1CE", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "3233", shade_name: "Grand Edifice", category: "Modern Midtones", color_family: "Pink", hex_color: "#CA998B", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "3302", shade_name: "Filigree Stone", category: "Modern Midtones", color_family: "Violet", hex_color: "#DFDAFC", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "3293", shade_name: "Tea Time Mauve", category: "Modern Midtones", color_family: "Violet", hex_color: "#AA8E9E", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "3343", shade_name: "Pewter Glint", category: "Modern Midtones", color_family: "Grey", hex_color: "#A2ACAE", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "3324", shade_name: "Indie Blues", category: "Modern Midtones", color_family: "Blue", hex_color: "#949ED4", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "3433", shade_name: "Hushed Slience", category: "Modern Midtones", color_family: "Green", hex_color: "#A2BAAC", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "3403", shade_name: "Hill Gorge", category: "Modern Midtones", color_family: "Green", hex_color: "#83A294", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "3502", shade_name: "Bamboo Hollow", category: "Modern Midtones", color_family: "Green", hex_color: "#BED7AC", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "3613", shade_name: "Chrysanthemum Tea", category: "Modern Midtones", color_family: "Green", hex_color: "#CED9B4", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },

  // --- Bold Accents (Interiors Page 4) ---
  { shade_code: "5011", shade_name: "Surprise Surprise", category: "Bold Accents", color_family: "Yellow", hex_color: "#FCF81F", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "5024", shade_name: "Radiant Air", category: "Bold Accents", color_family: "Yellow", hex_color: "#FCC53A", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "5042", shade_name: "Eye of the Sun", category: "Bold Accents", color_family: "Yellow", hex_color: "#FCAC17", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "5064", shade_name: "Accent Orange", category: "Bold Accents", color_family: "Orange", hex_color: "#FC761F", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "5101", shade_name: "Satin Sass", category: "Bold Accents", color_family: "Red", hex_color: "#E25950", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "5126", shade_name: "Run the Show", category: "Bold Accents", color_family: "Red", hex_color: "#C20C17", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "5171", shade_name: "Selfie World", category: "Bold Accents", color_family: "Pink", hex_color: "#FA9CB2", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "5164", shade_name: "L O E V Today", category: "Bold Accents", color_family: "Red", hex_color: "#9E062B", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "5181", shade_name: "Whimnasium", category: "Bold Accents", color_family: "Violet", hex_color: "#B775A8", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "5203", shade_name: "Indie Music", category: "Bold Accents", color_family: "Blue", hex_color: "#5479CE", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "5232", shade_name: "Free Fall", category: "Bold Accents", color_family: "Green", hex_color: "#5EA98D", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "5205", shade_name: "Electric Blue", category: "Bold Accents", color_family: "Blue", hex_color: "#4A3CE9", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "5263", shade_name: "Peace Network", category: "Bold Accents", color_family: "Green", hex_color: "#29CE4E", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "5215", shade_name: "Peacock Strut", category: "Bold Accents", color_family: "Grey", hex_color: "#034E43", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "5293", shade_name: "Para Gliding", category: "Bold Accents", color_family: "Green", hex_color: "#A2CE12", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 },
  { shade_code: "5307", shade_name: "Digital Shorts", category: "Bold Accents", color_family: "Yellow", hex_color: "#A2CE0F", pdf_source: "Colourvista Shade Palette - Interiors", pdf_page: 4 }
];
